Insert INTO Users (id, login, password, name, surname, permission_id) VALUES (1,'admin','admin', 'Michał', 'Kowalik', 1)
INSERT INTO Users (id, login, password, name, surname, permission_id) VALUES (2,'admin1','admin1', 'Anna', 'Huk', 1)
INSERT INTO Users (id, login, password, name, surname, permission_id) VALUES (3,'admin2','admin2', 'Mateusz', 'Hupa', 1)
INSERT INTO Users (id, login, password, name, surname, permission_id) VALUES (4,'admin3','admin3', 'Michał', 'Wójcik', 1)
INSERT INTO Users (id, login, password, name, surname, permission_id) VALUES (5,'admin4','admin4', 'Michal', 'Kowalik', 1)

INSERT INTO Users (id, login, password, name, surname, permission_id) VALUES (6,'j.kowalski','zaq1@WSX', 'Jan', 'Kowalski', 2)


INSERT INTO permissions (id, level, name) VALUES (1,1, 'admin')
INSERT INTO permissions (id, level, name) VALUES (2,2, 'receptionist')
INSERT INTO permissions (id, level, name) VALUES (3,3, 'doctor')
INSERT INTO permissions (id, level, name) VALUES (4,4, 'physiotherapist')
INSERT INTO permissions (id, level, name) VALUES (5,5, 'patient')



INSERT INTO ROOMS (id, floor, number,state) VALUES (1,1,1,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (2,1,2,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (3,1,3,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (4,1,4,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (5,1,5,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (6,1,6,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (7,1,7,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (8,1,8,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (9,1,9,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (10,1,10,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (11,1,11,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (12,1,12,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (13,1,13,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (14,1,14,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (15,1,15,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (16,1,16,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (17,1,17,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (18,1,18,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (19,1,19,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (20,1,20,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (21,1,21,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (22,1,22,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (23,1,23,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (24,1,24,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (25,1,25,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (26,1,26,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (27,1,27,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (28,1,28,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (29,1,29,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (30,1,30,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (31,2,1,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (32,2,2,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (33,2,3,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (34,2,4,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (35,2,5,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (36,2,6,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (37,2,7,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (38,2,8,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (39,2,9,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (40,2,10,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (41,2,11,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (42,2,12,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (43,2,13,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (44,2,14,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (45,2,15,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (46,2,16,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (47,2,17,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (48,2,18,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (49,2,19,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (50,2,20,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (51,2,21,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (52,2,22,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (53,2,23,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (54,2,24,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (55,2,25,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (56,2,26,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (57,2,27,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (58,2,28,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (59,2,29,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (60,2,30,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (61,3,1,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (62,3,2,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (63,3,3,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (64,3,4,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (65,3,5,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (66,3,6,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (67,3,7,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (68,3,8,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (69,3,9,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (70,3,10,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (71,3,11,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (72,3,12,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (73,3,13,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (74,3,14,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (75,3,15,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (76,3,16,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (77,3,17,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (78,3,18,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (79,3,19,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (80,3,20,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (81,3,21,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (82,3,22,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (83,3,23,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (84,3,24,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (85,3,25,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (86,3,26,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (87,3,27,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (88,3,28,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (89,3,29,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (90,3,30,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (91,4,1,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (92,4,2,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (93,4,3,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (94,4,4,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (95,4,5,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (96,4,6,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (97,4,7,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (98,4,8,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (99,4,9,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (100,4,10,'wolny')

INSERT INTO MEDICAMENTS (id, name, dose) VALUES (1,'Abra',47)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (2,'Accu-Chek Active',39)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (3,'Accu-Chek Instant',96)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (4,'Accu-Chek Performa',97)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (5,'Acidum folicum Hasco',78)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (6,'Acidum folicum Richter',84)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (7,'Acticoat Flex 3',53)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (8,'Actisorb Plus',13)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (9,'Adamon SR',74)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (10,'Adaptic',9)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (11,'Allevyn Adhesive',48)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (12,'Allevyn Ag Adhesive',66)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (13,'Allevyn Ag Heel',95)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (14,'Allevyn Ag Non Adhesive',41)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (15,'Allevyn Ag Sacrum',89)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (16,'Allevyn Heel',15)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (17,'Allevyn Life',71)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (18,'Allevyn Life Heel',97)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (19,'Allevyn Life Sacrum',30)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (20,'Allevyn Non Adhesive',91)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (21,'Allevyn Sacrum',77)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (22,'Amotaks',87)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (23,'Amoxicillin Aurovitas',74)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (24,'Anesderm',17)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (25,'Aprepitant Sandoz',42)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (26,'Aprepitant Teva',3)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (27,'Aquacel Ag',28)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (28,'Aquacel Ag Extra',26)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (29,'Aquacel Ag+ Extra',57)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (30,'Aquacel Ag Foam',1)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (31,'Aquacel Extra',40)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (32,'Aquacel Foam',11)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (33,'Aqua Gel',73)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (34,'Aqvitox D',38)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (35,'Arilin Rapid',84)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (36,'Aspulmo',24)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (37,'Atarax',60)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (38,'Atossa',20)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (39,'Atrodil',86)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (40,'Atrovent',88)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (41,'Atrovent N',83)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (42,'Bebilon Pepti 1 DHA',11)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (43,'Bebilon Pepti 2 DHA',47)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (44,'Bebilon Pepti 1 Syneo',99)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (45,'Bebilon Pepti 2 Syneo',42)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (46,'Biatain Adhesive',37)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (47,'Biatain Adhesive Heel',80)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (48,'Biatain Adhesive Sacral',72)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (49,'Biatain Ag Adhesive',12)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (50,'Biatain Ag Adhesive Heel',96)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (51,'Biatain Ag Adhesive Sacral',51)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (52,'Biatain Ag Non Adhesive',31)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (53,'Biatain Alginate Ag',70)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (54,'Biatain Non Adhesive',100)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (55,'Biatain Silicone',9)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (56,'Biatain Super Adhesive',95)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (57,'BTM SuperCheck 1',25)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (58,'Buventol Easyhaler',20)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (59,'CareSens N',39)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (60,'Cera-Chek 1 Code',66)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (61,'Clean WND',82)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (62,'Clotrimazolum GSK tabletki dopochwowe',57)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (63,'CoFlex TLC Calamine Lite',33)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (64,'CoFlex TLC Zinc Lite',69)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (65,'Contour Plus',47)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (66,'Contour TS',12)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (67,'Crotamiton Farmapol',43)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (68,'D+',49)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (69,'Dekristol',24)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (70,'Devikap',26)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (71,'Diagnostic Gold Strip',17)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (72,'Diagomat Strip',77)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (73,'Diavue ToGo',24)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (74,'Doreta',30)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (75,'Doxycyclinum Polfarmex',17)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (76,'Doxycyclinum TZF kapsuĹ‚ki',50)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (77,'Duomox',21)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (78,'Durafiber',21)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (79,'Emend',38)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (80,'EMLA',43)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (81,'Eusure',49)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (82,'Evercare',18)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (83,'Everchek',46)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (84,'Exbol',40)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (85,'Fibracol Plus',72)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (86,'Foam Lite Convatec',64)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (87,'G-BIO',64)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (88,'GensuCare',27)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (89,'Glucocard 01 Sensor',11)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (90,'Glucocard Vital Test Strip',70)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (91,'GlucoDr. auto - GlucoDr. auto A',78)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (92,'Glucomaxx',71)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (93,'Glucosense',17)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (94,'Glucosum Fresenius',44)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (95,'Glucosure HT',91)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (96,'Glukoza Braun',8)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (97,'Granuflex',93)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (98,'Granuflex Bordered',95)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (99,'Granuflex Extra Thin',97)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (100,'Granuflex pasta',27)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (101,'Granugel',42)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (102,'Hiconcil',100)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (103,'HydroClean plus',55)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (104,'HydroClean plus cavity',52)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (105,'Hydrocoll',9)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (106,'Hydrocoll Concave',49)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (107,'Hydrocoll Sacrall',15)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (108,'Hydrocoll Thin',13)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (109,'HydroTac',12)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (110,'HydroTac comfort',91)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (111,'Hydroxyzine Orion',12)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (112,'Hydroxyzinum Adamed',95)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (113,'Hydroxyzinum Alvogen',53)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (114,'Hydroxyzinum Espefa',16)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (115,'Hydroxyzinum Hasco',2)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (116,'Hydroxyzinum Polfarmex',85)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (117,'Hydroxyzinum PPH',43)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (118,'Hydroxyzinum VP',71)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (119,'Inadine',25)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (120,'Intrasite Gel',90)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (121,'iXell',73)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (122,'Juvit D3',89)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (123,'Lidocain-Egis',54)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (124,'Lidocaine Grindeks',87)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (125,'Lignocain',97)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (126,'Lignocainum hydrochloricum WZF',58)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (127,'Lignocainum Jelfa',10)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (128,'Lignox',53)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (129,'Lomatuell Pro',98)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (130,'Medisorb A',78)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (131,'Medisorb G',66)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (132,'Medisorb H',73)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (133,'Mepilex',44)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (134,'Mepilex Ag',90)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (135,'Mepilex Border',74)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (136,'Mepilex Border Ag',72)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (137,'Mepilex Border EM',31)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (138,'Mepilex EM',37)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (139,'Mepilex Talon',48)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (140,'Mepilex Transfer',9)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (141,'Mepitel',70)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (142,'Metronidazol Jelfa',100)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (143,'Metronidazol Polpharma tabletki dopochwowe',60)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (144,'Microdot',47)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (145,'Motti',72)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (146,'Multisure GK',33)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (147,'Natamycyna Unia',90)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (148,'Natrium chloratum 0',98)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (149,'Natrium chloratum 0',33)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (150,'Nutramigen 1 LGG',99)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (151,'Nutramigen 2 LGG',24)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (152,'Nutramigen 3 LGG',7)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (153,'Nystatyna Teva',69)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (154,'Nystatyna VP',17)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (155,'OKmeter Core',82)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (156,'Ondansetron Accord',58)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (157,'Ondansetron B. Braun',6)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (158,'Ondansetron Bluefish',54)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (159,'Ondansetron Kabi',28)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (160,'One Touch Select Plus',91)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (161,'Optilyte',29)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (162,'Optium Xido',51)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (163,'Ospamox',91)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (164,'Ospen',64)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (165,'Oxycort',79)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (166,'Padolten',41)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (167,'Palgotal',39)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (168,'Paratram',93)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (169,'Physiotulle Ag',53)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (170,'Pimafucin globulki',22)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (171,'PĹ‚yn Ringera Fresenius',8)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (172,'Poltram',37)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (173,'Poltram Combo',14)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (174,'Purilon Gel',87)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (175,'Rightest GS 100',36)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (176,'Ringer',64)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (177,'Rozex',2)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (178,'RoztwĂłr Ringera',68)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (179,'Sabumalin',14)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (180,'Setronon',12)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (181,'Silvercel Hydro-Alginate',36)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (182,'Sodium chloride-Braun',37)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (183,'Solderol',65)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (184,'Sorbact gel',3)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (185,'Sorbact kompres',20)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (186,'Sorbact opatrunek absorpcyjny',43)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (187,'Sorbact opatrunek piankowy',26)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (188,'Sorbact Superabsorbent',7)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (189,'Sorbact taĹ›ma z gazy',17)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (190,'Sorbalgon',94)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (191,'Sorelex',61)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (192,'Suprasorb A',36)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (193,'Suprasorb A + Ag',10)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (194,'Suprasorb C',53)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (195,'Suprasorb G',7)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (196,'Suprasorb H',60)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (197,'Suprasorb P',41)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (198,'Suprasorb X + PHMB',99)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (199,'Tielle',63)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (200,'Tielle Non Adhesive',1)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (201,'Torecan',90)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (202,'Tramadol Aurovitas',63)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (203,'Tramadol Krka',80)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (204,'Tramadol + Paracetamol Genoptim',5)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (205,'Tramadol Synteza',82)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (206,'Tramadol Vitabalans',55)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (207,'Tramal',79)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (208,'Tramapar',79)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (209,'Tramundin',26)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (210,'Trimesan',98)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (211,'Unidox Solutab',6)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (212,'UrgoClean',57)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (213,'UrgoClean Ag',57)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (214,'UrgoClean Rope',16)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (215,'UrgoStart Contact',5)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (216,'UrgoStart Plus Border',12)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (217,'UrgoStart Plus Pad',33)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (218,'UrgoTul',12)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (219,'UrgoTul Absorb',94)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (220,'UrgoTul Absorb Border',8)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (221,'UrgoTul Absorb Border Sacrum',40)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (222,'UrgoTul Absorb Heel',73)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (223,'UrgoTul Ag/Silver',31)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (224,'Urotrim',85)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (225,'Ventolin',98)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (226,'Ventolin Dysk',33)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (227,'Vermox',71)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (228,'Versatis',53)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (229,'VivaChek Ino',26)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (230,'Vliwaktiv',3)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (231,'Vliwaktiv Ag',13)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (232,'Vliwasorb adhesive',100)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (233,'Vliwasorb Pro',82)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (234,'Wellion SymPhar',23)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (235,'Xylocaine',29)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (236,'Zaldiar',39)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (237,'Zetuvit Plus',60)
INSERT INTO MEDICAMENTS (id, name, dose) VALUES (238,'Zofran',3)





