Insert INTO Users (id, login, password, name, surname, permission_id) VALUES (1,'admin','admin', 'Michał', 'Kowalik', 1)
INSERT INTO Users (id, login, password, name, surname, permission_id) VALUES (2,'admin1','admin1', 'Anna', 'Huk', 1)
INSERT INTO Users (id, login, password, name, surname, permission_id) VALUES (3,'admin2','admin2', 'Mateusz', 'Hupa', 1)
INSERT INTO Users (id, login, password, name, surname, permission_id) VALUES (4,'admin3','admin3', 'Michał', 'Wójcik', 1)
INSERT INTO Users (id, login, password, name, surname, permission_id) VALUES (5,'admin4','admin4', 'Michal', 'Kowalik', 1)

INSERT INTO Users (id, login, password, name, surname, permission_id) VALUES (6,'j.kowalski','zaq1@WSX', 'Jan', 'Kowalski', 2)


INSERT INTO permissions (id, level, name) VALUES (1,1, 'admin')
INSERT INTO permissions (id, level, name) VALUES (2,2, 'receptionist')
INSERT INTO permissions (id, level, name) VALUES (3,3, 'doctor')
INSERT INTO permissions (id, level, name) VALUES (4,4, 'physiotherapist')
INSERT INTO permissions (id, level, name) VALUES (5,5, 'patient')



INSERT INTO ROOMS (id, floor, number,state) VALUES (1,1,1,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (2,1,2,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (3,1,3,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (4,1,4,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (5,1,5,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (6,1,6,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (7,1,7,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (8,1,8,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (9,1,9,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (10,1,10,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (11,1,11,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (12,1,12,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (13,1,13,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (14,1,14,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (15,1,15,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (16,1,16,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (17,1,17,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (18,1,18,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (19,1,19,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (20,1,20,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (21,1,21,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (22,1,22,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (23,1,23,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (24,1,24,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (25,1,25,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (26,1,26,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (27,1,27,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (28,1,28,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (29,1,29,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (30,1,30,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (31,2,1,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (32,2,2,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (33,2,3,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (34,2,4,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (35,2,5,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (36,2,6,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (37,2,7,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (38,2,8,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (39,2,9,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (40,2,10,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (41,2,11,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (42,2,12,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (43,2,13,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (44,2,14,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (45,2,15,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (46,2,16,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (47,2,17,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (48,2,18,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (49,2,19,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (50,2,20,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (51,2,21,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (52,2,22,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (53,2,23,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (54,2,24,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (55,2,25,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (56,2,26,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (57,2,27,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (58,2,28,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (59,2,29,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (60,2,30,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (61,3,1,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (62,3,2,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (63,3,3,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (64,3,4,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (65,3,5,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (66,3,6,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (67,3,7,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (68,3,8,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (69,3,9,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (70,3,10,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (71,3,11,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (72,3,12,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (73,3,13,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (74,3,14,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (75,3,15,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (76,3,16,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (77,3,17,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (78,3,18,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (79,3,19,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (80,3,20,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (81,3,21,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (82,3,22,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (83,3,23,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (84,3,24,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (85,3,25,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (86,3,26,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (87,3,27,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (88,3,28,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (89,3,29,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (90,3,30,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (91,4,1,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (92,4,2,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (93,4,3,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (94,4,4,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (95,4,5,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (96,4,6,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (97,4,7,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (98,4,8,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (99,4,9,'wolny')
INSERT INTO ROOMS (id, floor, number,state) VALUES (100,4,10,'wolny')
